name: Bi-Monthly Dependency Update

on:
  schedule:
    - cron: '0 0 1 */2 *'
  workflow_dispatch: 

jobs:
  update_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '19.8.1'  

      - name: Install npm-check-updates
        run: npm install -g npm-check-updates

      - name: Update frontend dependencies
        working-directory: frontend
        run: |
          ncu -u --target minor  
          npm ci  

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.2' 

      - name: Update backend dependencies
        working-directory: backend
        run: |
          pip install -r requirements.txt
          pip list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1 | xargs -n1 pip install -U
          pip freeze > requirements.txt 

      - name: Run backend tests
        working-directory: backend
        run: |
          python manage.py test || echo "Backend tests failed" >> error_log.txt

      - name: Build project
        working-directory: frontend
        run: |
          npm run build || echo "Frontend build failed" >> error_log.txt

      - name: Run frontend tests
        working-directory: frontend
        run: |
          npm run test:local || echo "Frontend tests failed" >> error_log.txt

      - name: Type check
        working-directory: frontend
        run: |
          npm run typecheck || echo "Frontend typecheck failed" >> error_log.txt

      - name: Lint code
        working-directory: frontend
        run: |
          npm run lint || echo "Frontend linting failed" >> error_log.txt

      - name: Format code
        working-directory: frontend
        run: |
          npm run format || echo "Frontend formatting failed" >> error_log.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: "Bi-Monthly Dependency Update"
          body: |
            Automated bi-monthly dependency update.
            - Updated frontend and backend dependencies to the latest minor versions.
            - See below for the results of the build, typecheck, and test runs.
          branch: "dependency-update-$(date +'%Y%m%d')" 

      - name: Notify Team via Matrix
        uses: fadenb/matrix-chat-message@v0.0.6
        with:
          homeserver: 'matrix.org'
          token: ${{ secrets.MATRIX_TOKEN }}
          channel: '!CRgLpGeOBNwxYCtqmK:matrix.org'
          message: |
            Bi-monthly dependency update PR created. Please review it and check for any issues!

      - name: Log Errors
        if: failure() 
        run: |
          if [[ -f error_log.txt ]]; then
            cat error_log.txt
          else
            echo "No errors found during dependency update."
          fi

      - name: Create GitHub Issue
        if: failure()
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Dependency Update Errors
          content-filepath: error_log.txt
