name: pr_ci_backend
on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  checks: write
  pull-requests: write

env:
  SECRET_KEY: "ONLY_FOR_TESTING"
  DATABASE_PORT: 5432
  DATABASE_HOST: localhost
  DATABASE_NAME: postgres
  DATABASE_USER: postgres
  DATABASE_PASSWORD: postgres

jobs:
  backend:
    services:
      postgres:
        image: postgres:13
        env:
            POSTGRES_USER: ${{ env.DATABASE_USER }}
            POSTGRES_PASSWORD: ${{ env.DATABASE_PASSWORD }}
            POSTGRES_DB: ${{ env.DATABASE_NAME }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    name: Run PR Backend Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade uv
          uv venv
          uv pip install -r backend/requirements-dev.txt

      - name: Activate Virtual Environment
        run: |
          . .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV

      - name: Run Ruff Format - Formatting Check
        run: ruff format ./backend

      - name: Run Ruff - Linting and Import Sorting Check
        if: always()
        run: ruff check ./backend

      - name: Run mypy - Static Type Checking
        if: always()
        run: mypy ./backend --config-file ./backend/pyproject.toml

      - name: Run pytest - Unit Tests
        if: always()
        run: pytest ./backend -vv

      - name: Run Django Migrations - Database Migrations Check
        run: |
          . .venv/bin/activate
          python ./backend/manage.py makemigrations
          python ./backend/manage.py migrate

      - name: Build Coverage File
        run: |
          pytest ./backend --cov=backend --junitxml=pytest.xml --cov-report=xml --cov-report=term --cov-fail-under=70 | tee pytest-coverage.txt
        continue-on-error: false

      - name: Pytest Coverage Comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: pytest-coverage.txt
          junitxml-path: pytest.xml
