name: pr_ci_backend
on:
  pull_request_target:
    branches:
      - main
    types: [opened, reopened, synchronize]
  workflow_run:
    workflows: [pr_maintainer_checklist]
    types:
      - completed

jobs:
  python:
    name: Run PR Backend Formatting Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run Black
        uses: psf/black@stable
        with:
          options: --check --verbose --exclude "migrations/"
          src: ./backend

      - name: Run ruff
        run: ruff ./backend

      - name: Run mypy - Static Type Checking
        run: mypy ./backend --config-file ./backend/mypy.ini
